openapi: 3.0.0
info:
  title: Shared User Schema
  version: 1.0.0
components:
  schemas:
    UserRole:
      type: string
      enum:
        - trainer
        - client
        - admin

    TrainerProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        qualifications:
          type: array
          items:
            type: string
        specializations:
          type: array
          items:
            type: string
        experience_years:
          type: integer
        bio:
          type: string
        rating:
          type: number
          format: float

    ClientProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        subscription_status:
          type: string
        subscription_expires:
          type: string
          format: date-time
        goals:
          type: array
          items:
            type: string
        fitness_level:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        role:
          $ref: '#/components/schemas/UserRole'
        is_active:
          type: boolean
          default: true
        phone:
          type: string
        telegram_id:
          type: string
        preferences:
          type: object
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        client_profile:
          $ref: '#/components/schemas/ClientProfile'
        trainer_profile:
          $ref: '#/components/schemas/TrainerProfile'
      required:
        - id
        - email
        - name
        - role
        - created_at
        - updated_at 