# Netlify configuration for monorepo deployment

# Main site configuration (Client App)
[build]
  publish = "apps/client-app/build"
  command = "npm run client:build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Headers for PWA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# PWA files
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Context-specific builds for different branches
[context.deploy-preview]
  command = "npm run client:build"

[context.branch-deploy]
  command = "npm run client:build"

# Production environment variables
[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_VERSION = "1.0.0" 