# generated by datamodel-codegen:
#   filename:  user.v1.yaml
#   timestamp: 2025-06-16T11:19:18+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, EmailStr


class UserRole(Enum):
    trainer = 'trainer'
    client = 'client'
    admin = 'admin'


class TrainerProfile(BaseModel):
    id: Optional[UUID] = None
    qualifications: Optional[List[str]] = None
    specializations: Optional[List[str]] = None
    experience_years: Optional[int] = None
    bio: Optional[str] = None
    rating: Optional[float] = None


class ClientProfile(BaseModel):
    id: Optional[UUID] = None
    subscription_status: Optional[str] = None
    subscription_expires: Optional[datetime] = None
    goals: Optional[List[str]] = None
    fitness_level: Optional[str] = None


class User(BaseModel):
    id: UUID
    email: EmailStr
    name: str
    role: UserRole
    is_active: Optional[bool] = True
    phone: Optional[str] = None
    telegram_id: Optional[str] = None
    preferences: Optional[Dict[str, Any]] = None
    created_at: datetime
    updated_at: datetime
    client_profile: Optional[ClientProfile] = None
    trainer_profile: Optional[TrainerProfile] = None
